### ISSUE TITLE
Rounded buttons have round corners next to inputs

### ISSUE THREAD

**Issue by kwalker3690** [optimizely/oui#137]
<img width="302" alt="screenshot 2015-09-23 18 51 00" src="https://cloud.githubusercontent.com/assets/2287470/10063619/d6656b7c-6224-11e5-8fd7-cf97db424513.png">

**Comment by tomgenoni** [comment]
The problem here is that the button/input are double nested inside a `lego-button-group`. Need to remove the outer one.

**Comment by danoc** [comment]
Reopening this one because I'm reverting it until we have time to fix a regression it introduced.

<img width="603" alt="screenshot 2016-04-11 17 47 03" src="https://cloud.githubusercontent.com/assets/916038/14446682/75effece-000d-11e6-8cf0-05113dede49f.png">

The change to the selector in `_button-group.scss` was causing it to target items within the dropdown that is within a button group. The position relative (added on hover and focus) breaks the dropdowns.
