### ISSUE TITLE
Fix the vertical spacing of nested lists

### ISSUE THREAD

**Issue by nchilada** [optimizely/oui#208]
When a list contains a nested list as well as other content, we see more space above the nested list than below.  This is manifest in the [developer docs](http://developers.optimizely.com/javascript/personalization/index.html#getAttributeValue), at least.

This seems to be the offending declaration: https://github.com/optimizely/oui/blob/c573d2d2256064c99f5536806cd5b9a7efcd7c6f/src/oui/partials/base/_lists.scss#L52

I'd send a pull request, but I'm not sure what the correct solution would be.  `0` for both `margin-top` and `margin-bottom`?  Or maybe half of the usual height for both?  Or maybe the existing declaration just needs a more restrictive selector, such that it no longer applies to lists in the developer docs?

**Comment by tomgenoni** [comment]
@nchilada Some context...this is a question of defaults. In the app we use lists (ul/ol) almost exclusively for nav elements or other lists that aren't really "lists". Given that that's the most common use case we elected to make sure they worked as expected. You can use `push--bottom` classes to get the spacing you want (if I'm understanding your issue correctly).

However, when using the list variation classes I think we can add margins since in that case spacing is expected. I'll take a look.

**Comment by tscanlin** [comment]
@tomgenoni I understand the reasoning for this rule and I think in this case it probably just makes sense for me to add an override rule to the developer documentation site. The reason using classes to override this is not ideal is because the HTML is being generated from markdown so adding classes isn't very easy unless we mix HTML with markdown which we want to avoid.

I'd say close this issue and I can make a new one for the dev docs.

Thanks for the reply!

**Comment by nchilada** [comment]
@tomgenoni @tscanlin thanks, works for me!
