### ISSUE TITLE
The link to ScribeSass in the readme points to a 404 page

### ISSUE THREAD

**Issue by kaelig** [optimizely/oui#359]
Looks like https://github.com/optimizely/scribesass is a private repository?

**Comment by danoc** [comment]
Heh, yes it is. We should just remove the link for now or add a note that it is private. I'd like to open source it in the future but it's far from ready and I can't prioritize that work now.

**Comment by danoc** [comment]
I've added a note that the repository is currently private. 

Hoping to make big improvements to it in the future once the dust settles on our React project and then open source it. Maybe I can use the new [scss-parser](https://github.com/salesforce-ux/scss-parser) your team created instead of relying on gonzales-pe.
