### ISSUE TITLE
Avoid BEM nesting in Sass

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#364]
Sass 3.3 introduced a feature that allows developers to [nest their SCSS](http://alwaystwisted.com/articles/2014-02-27-even-easier-bem-ing-with-sass-33). This leads to cleaner looking SCSS files that look like this:

``` scss
.block {
    &__element { ... }
    &--modifier { ... }
}
```

The downside is that it makes the code very heard to search for. If I wanted to rename `.block__element` to `.foo__bar`, I'd have to search for `.foo`, `__bar`, `.foo__bar`, and `foo__bar` to find all instances in the HTML and SCSS. 

This is bad for a few reasons:
1. It becomes harder to confidently find and replace which is important in a growing codebase with dozens of developers.
2. Engineers that don't know about BEM SCSS nesting will have a hard time finding where a rule is defined. (I've seen this happen a few times when helping others debug.)

@mdo also writes about this in his post "[Nesting in Sass and Less](http://markdotto.com/2015/07/20/css-nesting/#bem-nesting-with-)".

I think the downsides of a less searchable codebase far outweigh the benefit of nicer looking SCSS files.

---

@kwalker3690, @daverau-optimizely, @tscanlin – What do you all think? This is somewhat related to the goal of #361.

**Comment by daverau-optimizely** [comment]
Would we write them adjacent, like this?
```
.block__element { ... }
.block--modifier { ... }
```
Or is there another approach?

**Comment by tscanlin** [comment]
I think I'd disagree that nicer looking scss files is more important than a more searchable codebase.

In my mind, this basically boils down to:
"should we emphasize making code easier to write or easier to read"

I'd argue that it's usually more important to make code easier to read since reading the code is probably a more common action than writing it. Additionally, the shorthand for nesting in SASS doesn't really save that many characters, but being able to do global searches for a class and get good results is really really nice. Most editors support find/replace or multiple cursors which makes SASS / BEM shorthand even less of a benefit.

That being said, this would be a huge effort since things are mostly written w/ shorthand now, I haven't heard many complaints from other users mentioning that they want global searches to be better, and you prefer keeping it as it is now. So I'd say I don't feel *too* strongly that we should switch.

**Comment by danoc** [comment]
@daverau-optimizely – Yeah, that would be the approach. What do you think?

@tscanlin – Not sure if you were disagreeing with me, but I think we're both on the same page?

> I think I'd disagree that nicer looking scss files is more important than a more searchable codebase.

Regardless, 👍 to all of you points. It's probably not worth doing a huge refactor of everything, but it's something we could enforce going forward if we're all on the same page. (Maybe there's a linter config for this.)

**Comment by tscanlin** [comment]
Yeah, I'd be curious if Kelly or Dave have strong opinions either way. But I agree that doing a huge refactor probably doesn't make sense. Let's keep as is unless you see a need to switch.

**Comment by tscanlin** [comment]
Oh, lol. I just realized now that you were totally advocating for switching over to the more searchable style. Something about the way this is worded threw me off.

> I think the downsides of a less searchable codebase far outweigh the benefit of nicer looking SCSS files.

So yes, we are totally in agreement, sorry for the confusion. :)

**Comment by daverau-optimizely** [comment]
When we do this, setup a script/test to check output against original for identical output.
