### ISSUE TITLE
Should select default color should be the color of placeholders?

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#391]
<img width="900" alt="screenshot 2016-05-02 13 40 38" src="https://cloud.githubusercontent.com/assets/916038/14967305/8221c59c-106b-11e6-9b0b-79ca41efb31e.png">

Should selects have the notion of a placeholder? Or should we be defaulting to a value? An example of a placeholder would be if the first value in the dropdown says something like "Choose date...".

cc: @zleach (@asaschachar ran into something like this recently), @daverau-optimizely, @kwalker3690, @tscanlin

**Comment by tscanlin** [comment]
@danoc I think a placeholder option should be allowed but not a requirement. Were you thinking it should be a requirement?

**Comment by danoc** [comment]
@tscanlin – I don't really have any strong thoughts other than we should probably somehow support the notion of a placeholder.

**Comment by tscanlin** [comment]
Yeah, I agree. Maybe we could just try and add some css such as:
```
select[value=""] {
  color: $gray
}
```

Need to test though.

**Comment by daverau-optimizely** [comment]
Placeholder text is different because it's not submitted as the default value, but a select is, which I think changes the intent of the text, and therefore the color. I could see a case where the text is optional, but something about the grey text makes it feel disable or inactive, and not emphasizing the choice you're making.

Live code example: http://codepen.io/optidave/pen/QNJxVq?editors=1000

And screenshot: 
<img width="203" alt="screenshot 2016-05-02 16 14 43" src="https://cloud.githubusercontent.com/assets/16581943/14970815/fb87cc96-1080-11e6-8e61-22139e77ef03.png">

**Comment by daverau-optimizely** [comment]
The light grey text color works in the case of an optional select where the choice isn't your selected state, like 'Choose your state...' but as soon as you choose 'California' the grey text doesn't make clear that's the active choice, it looks disabled.

What's a case where this would be desirable?

**Comment by tscanlin** [comment]
I think the reason this was brought up is because selects look different than all the other input's with gray placeholders. I agree with your analysis that it looks disabled when gray and I was only saying it should show up as gray when the option has no value and would presumably be a placeholder value.

But I think the risk of this change making select's look disabled should be enough reason to keep from making this change unless user feedback indicates that we should.

**Comment by daverau-optimizely** [comment]
@tscanlin good point — we could use JS to change the grey once you select something besides the placeholder value. Seems like a legit use case then.
