### ISSUE TITLE
Create a Table style with more padding

### ISSUE THREAD

**Issue by danoc** [optimizely/oui#536]
The tables in our product often have more spacing in the `<td>`'s. I think we should move the product overrides into OUI and provide a prop for `Table` and modifier for `_table.scss`.

cc: @mikeng13 who requested this.

**Comment by danoc** [comment]
Proposed API:

```
<Table density='cozy'></Table>
<Table density='compact'></Table>
```

`compact` would be the `defaultValue`.

@mikeng13 – What do you think?

**Comment by daverau-optimizely** [comment]
What's the goal, to have more compact tables? A compact option seems reasonable then.

`cozy` and `compact` strike me as too similar sounding. But personally I find that gmail setting mostly useless as the roomy spaced option is very nice without adding crazy amounts of vertical space.

Can we can look at light and heavy content options to get a sense of range and tradeoffs in spacing? Having some screen shots of what the problem is and how we might fix it could help clarify the issue as well.

**Comment by danoc** [comment]
Let's chat about this some more in person!

**Comment by danoc** [comment]
@mikeng13 – We decided to do:

```
<Table density="tight">
<Table density="loose">
```

`tight` will be the `defaultValue`.

**Comment by mikeng13** [comment]
Sounds good to me @danoc
