### ISSUE TITLE
Fix attention warning

### ISSUE THREAD

**Issue by daverau-optimizely** [optimizely/oui#729]
Per @amy-chiu:
Warning: Failed propType: Invalid prop `children` of type `array` supplied to `Attention`, expected `string`. Check the render method of `snippetConfigDialog`.

**Comment by raykhenberg** [comment]
Another ping for this, can we just allow attention to use PropTypes.node?

**Comment by daverau-optimizely** [comment]
Hey @raykhenberg can you attach some JSX to show how you're able to trigger this warning? We can fix this ASAP and make a new release for you!

**Comment by raykhenberg** [comment]
Hey @daverau-optimizely this was actually resolved in a PR that I put out https://github.com/optimizely/oui/commit/c0a0618e380a811bea9e96e39a63af70dc25fdba

But if you simply do something like:

```
<Attention>
  <p>This is a <Link href='https://www.google.com'>link</Link> to Google</p>
</Attention
```
it should give you a warning because it only allowed strings. Amy's original issue might have been that she was passing an array of nodes, so hopefully this addresses that as well.

**Comment by daverau-optimizely** [comment]
Thanks Ricky, I see your fix now! Sorry, I was out on vaca during that PR. Closing this and will push a new release shortly.
